Added Node.js workflow.
icecube/NuCat pull request #12
Opened 2021-05-13 16:14 UTC by AdvaitDhingra

I have set up and tested the node.js workflow. I have modified it to work with NuCat. It tests both the client and the server side.

Shold fix [this](https://github.com/icecube/NuCat/issues/11) issue.

2021-05-13 16:16 UTC, AdvaitDhingra commented
Took quite a few commits, but it works

2021-05-14 01:15 UTC, ChujieChen commented on .github/workflows/node.js.yml
> +name: Test chnages (Node.js)
Let's keep the name simple: 'NodeJS'

2021-05-14 01:29 UTC, ChujieChen requested changes
Hey @AdvaitDhingra . Thank you for your code! This YMAL didn't work. Those four `npm run` lines never got a chance to run. Please revise this file. Also please follow the `CONTRIBUTING.md` for future PRs.

2021-05-14 01:29 UTC, ChujieChen commented on .github/workflows/node.js.yml
> +        node-version: 12.18.3
How about: `12.x`

2021-05-14 01:29 UTC, ChujieChen commented on .github/workflows/node.js.yml
> +        node-version: 12.18.3
same here

2021-05-14 01:29 UTC, ChujieChen commented on .github/workflows/node.js.yml
> +    - run: npm --prefix /client run build
The above two lines did not work. They cause errors:
```
Run npm --prefix /client ci
npm --prefix /client ci
shell: /usr/bin/bash -e {0}
Error: EACCES: permission denied, mkdir '/client'
```

2021-05-14 01:29 UTC, ChujieChen commented on .github/workflows/node.js.yml
> +    - run: npm --prefix /server run server
Same here. The above two lines never worked.

2021-05-14 07:00 UTC, AdvaitDhingra commented
Thanks for the review. I'll fix theses errors.

2021-06-15 06:57 UTC, ChujieChen commented
Hi @AdvaitDhingra , the workflow never gets run. And thus, I'm closing this PR. Please follow the [CONTRIBUTING.md](https://github.com/icecube/NuCat/blob/main/CONTRIBUTING.md) for future PRs (try squashing your commits with rebase -i to avoid a long list of commits). Thank you!

2021-06-15 06:57 UTC, closed without merging